name: Connection Test

on: [push, pull_request]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    container: 
      image: quay.io/eggplantsoftware/fusion-engine-ubi8:23.5.102
      options: --user root
    environment: default
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run connection test
        env:
          RDPHOSTNAME: ${{ vars.RDPHOSTNAME }}
          RDPPORT: ${{ vars.RDPPORT }}
          RDPUSERNAME: ${{ vars.RDPUSERNAME }}
          RDPPASSWORD: ${{ secrets.RDPPASSWORD }}
          RDPDOMAIN: ${{ vars.RDPDOMAIN }}
          EPF_LICENSE_KEY: ${{ secrets.EPF_LICENSE_KEY }}
        run: |
              defaults write Eggplant AcceptEULA YES
              defaults write Eggplant AcceptPrivacyAgreement YES
              defaults write Eggplant GSBackend libgnustep-headless
              defaults write Eggplant BonjourDiscoveryEnabled false
              runscript -LicenseKey "$EPF_LICENSE_KEY"
              mkdir -p ConnectionTest.suite/Scripts
              echo "CaptureScreen Name: "${pwd}/ConnectionTestScreenshot.png" > ConnectionTest.suite/Scripts/ConnectionTest.script
              runscript -type RDP -host $RDPHOSTNAME -port $RDPPORT -username $RDPUSERNAME -password $RDPPASSWORD ConnectionTest.suite/Scripts/ConnectionTest.script
      - name: Upload Connection Test Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
            name: Connection Test Screenshot
            path: ./ConnectionTestScreenshot.png